### ISSUE TITLE
Buildspace phaser issues

### ISSUE THREAD

**Issue by sbot50** [DFOnline/CodeClient#43]
1. Doesn't work in actual build mode
2. You lose your sprint if you accidentally unphase and cant sprint while phasing
3. Not an issue but add a way to make it a toggle
4. assuming you do 3, add a way to make it enabled by default

**Comment by GeorgeRNG** [comment]
1. It uses locations to teleport.
2. Spectator mode issue, and is an issue.
3. If I do I want to make the hand transparent to telegraph that you are phasing, since you shouldn't interact while it's enabled.
4. Again you can't interact, since the server player doesn't move and is teleported when you finish it

**Comment by GeorgeRNG** [comment]
Cannot replicate 2, I'll neglect 3 due to the nature of the feature
