### ISSUE TITLE
noclip breaks mega plot codespace

### ISSUE THREAD

**Issue by Geodafence** [DFOnline/CodeClient#88]
**Describe the bug**
Using noclip, you are unable to reach the extra codespace given by a mega.

**To Reproduce**
1. Enable noclip
2. Enter a megaplot with dev mode
3. Attempt to go to the extra codespace a mega plot gives

**Expected behavior**
You can go to it with no issues

**Screenshots**
![image](https://github.com/user-attachments/assets/e0018c2b-5dbf-4d3e-b938-a2dfe8dc89a4)

**Checks**
Please check all these for more infomation with the bug.
- [X] I am using the [latest version](https://github.com/DFOnline/CodeClient/releases).
- [X] I have tried disabling various options to see if they cause the issue, such as new ones or ones I have recently enabled.

**Comment by GeorgeRNG** [comment]
this is because of the improper stone on the floor.  
remove them by running:
- `/plot codespace underground create`
- `/plot codespace underground remove`

This should allow codeclient to correctly detect the size.  
You can also use `/worldplot mega` to override the detected plot size. <sub>the command name is a misnomer, from older versions</sub>

**Comment by GeorgeRNG** [comment]
Closing this because I've gotten no response and the issue is almost definitely the stone
